### ISSUE TITLE
jar包的下载命令是什么

### ISSUE THREAD

**Issue by wangweichaot** [zhaoxilingcheng/jd_maotai_rpa#1]
到项目所在目录，按照shift键打开命令窗口，执行  pip install -r requirements.txt

**Comment by wangweichaot** [comment]
eclipse下载的

**Comment by zhaoxilingcheng** [comment]
1. 不涉及jar包
2. cmd中使用  pip install -r requirements.txt 或者  pip3 install -r requirements.txt安装pipy依赖包即刻
3. 如果不会使用python, 直接在tag中下载exe文件直接执行也可

**Comment by wangweichaot** [comment]
谢谢，那命令执行了，已经起来了
